export
    const initialLotesArray = [
        {
            id: 'Lote001',
            origen: {
                hatcheryName: 'Aquamax',
                htCode: 'HT-2524',
                nurseryName: 'Texcumar',
                nurseryHtCode: 'HT-2525',
                naupliiCode: 'Chicpin K1',
                plantingDate: '10/02/24',
                harvestDate: '15/08/24',
                moduleNumber: 1,
                tankPondNumber: 1,
                densityPerM3: '100.000',
            },
            farm: {
                farmName: 'ShrimpCo Manabi',
                grCode: 'GR-5247',
                growingProtocol: 'Semi Intensive',
                productionProtocol: 'TriPhasic',
                waterManagingSystem: 'RAS',
                nurseryPond: 'Ppc#2',
                plantingDate: '12/02/24',
                initialNurseryDensity: 100,
                preGrowingPond: 'Ppe#3',
                transferDate: '20/04/24',
                initialPreGrowingDensity: 45,
                finalPreGrowingPond: 'Pef#34',
                finalTransferDate: '05/06/24',
                finalPreGrowingDensity: 15,
            },
            produccion: {
                feedMillHatchery: 'SCI-R004304',
                feedMillFarm: 'SCI-R004304',
            },
            tratamiento: {
                antibioticTreatment: 'SCI-R008978',
                initialDate: '01/03/24',
                endingDate: '15/03/24',
            },
            condiciones: {
                salinityPpm: 17,
                waterSourceType: 'Brackish',
                cycleWaterUse: '1750 m3/Ha',
                co2Footprint: '0.28 KgCO2/Shrimp Kg',
            },
            cosecha: {
                harvestProcess: 'Conventional',
                harvestDate: '15/08/24',
                harvestDensity: '8 u/m2',
                harvestTimeLapse: '02:30:45',
                harvestTemperature: '-6ºC',
            },
            custodia: {
                custodyTransportTimeLapse: '02:00:00',
                custodyTransportTemperature: '-4ºC',
                plantRegistryTemperature: '-4ºC',
            },
            calidad: {
                qualityLabTest: 'Approved',
                organolepticLabTest: 'Approved',
                sulphitesLabTest: 'Approved',
                microbiologicalLabTest: 'Approved',
                chemicalLabTest: 'Approved',
            },
        },
        {
            id: 'Lote001',
            origen: {
                hatcheryName: 'Aquamax',
                htCode: 'HT-2524',
                nurseryName: 'Texcumar',
                nurseryHtCode: 'HT-2525',
                naupliiCode: 'Chicpin K1',
                plantingDate: '10/02/24',
                harvestDate: '15/08/24',
                moduleNumber: 1,
                tankPondNumber: 1,
                densityPerM3: '100.000',
            },
            farm: {
                farmName: 'ShrimpCo Manabi',
                grCode: 'GR-5247',
                growingProtocol: 'Semi Intensive',
                productionProtocol: 'TriPhasic',
                waterManagingSystem: 'RAS',
                nurseryPond: 'Ppc#2',
                plantingDate: '12/02/24',
                initialNurseryDensity: 100,
                preGrowingPond: 'Ppe#3',
                transferDate: '20/04/24',
                initialPreGrowingDensity: 45,
                finalPreGrowingPond: 'Pef#34',
                finalTransferDate: '05/06/24',
                finalPreGrowingDensity: 15,
            },
            produccion: {
                feedMillHatchery: 'SCI-R004304',
                feedMillFarm: 'SCI-R004304',
            },
            tratamiento: {
                antibioticTreatment: 'SCI-R008978',
                initialDate: '01/03/24',
                endingDate: '15/03/24',
            },
            condiciones: {
                salinityPpm: 17,
                waterSourceType: 'Brackish',
                cycleWaterUse: '1750 m3/Ha',
                co2Footprint: '0.28 KgCO2/Shrimp Kg',
            },
            cosecha: {
                harvestProcess: 'Conventional',
                harvestDate: '15/08/24',
                harvestDensity: '8 u/m2',
                harvestTimeLapse: '02:30:45',
                harvestTemperature: '-6ºC',
            },
            custodia: {
                custodyTransportTimeLapse: '02:00:00',
                custodyTransportTemperature: '-4ºC',
                plantRegistryTemperature: '-4ºC',
            },
            calidad: {
                qualityLabTest: 'Approved',
                organolepticLabTest: 'Approved',
                sulphitesLabTest: 'Approved',
                microbiologicalLabTest: 'Approved',
                chemicalLabTest: 'Approved',
            },
        },
        {
            id: 'Lote001',
            origen: {
                hatcheryName: 'Aquamax',
                htCode: 'HT-2524',
                nurseryName: 'Texcumar',
                nurseryHtCode: 'HT-2525',
                naupliiCode: 'Chicpin K1',
                plantingDate: '10/02/24',
                harvestDate: '15/08/24',
                moduleNumber: 1,
                tankPondNumber: 1,
                densityPerM3: '100.000',
            },
            farm: {
                farmName: 'ShrimpCo Manabi',
                grCode: 'GR-5247',
                growingProtocol: 'Semi Intensive',
                productionProtocol: 'TriPhasic',
                waterManagingSystem: 'RAS',
                nurseryPond: 'Ppc#2',
                plantingDate: '12/02/24',
                initialNurseryDensity: 100,
                preGrowingPond: 'Ppe#3',
                transferDate: '20/04/24',
                initialPreGrowingDensity: 45,
                finalPreGrowingPond: 'Pef#34',
                finalTransferDate: '05/06/24',
                finalPreGrowingDensity: 15,
            },
            produccion: {
                feedMillHatchery: 'SCI-R004304',
                feedMillFarm: 'SCI-R004304',
            },
            tratamiento: {
                antibioticTreatment: 'SCI-R008978',
                initialDate: '01/03/24',
                endingDate: '15/03/24',
            },
            condiciones: {
                salinityPpm: 17,
                waterSourceType: 'Brackish',
                cycleWaterUse: '1750 m3/Ha',
                co2Footprint: '0.28 KgCO2/Shrimp Kg',
            },
            cosecha: {
                harvestProcess: 'Conventional',
                harvestDate: '15/08/24',
                harvestDensity: '8 u/m2',
                harvestTimeLapse: '02:30:45',
                harvestTemperature: '-6ºC',
            },
            custodia: {
                custodyTransportTimeLapse: '02:00:00',
                custodyTransportTemperature: '-4ºC',
                plantRegistryTemperature: '-4ºC',
            },
            calidad: {
                qualityLabTest: 'Approved',
                organolepticLabTest: 'Approved',
                sulphitesLabTest: 'Approved',
                microbiologicalLabTest: 'Approved',
                chemicalLabTest: 'Approved',
            },
        },
        {
            id: 'Lote001',
            origen: {
                hatcheryName: 'Aquamax',
                htCode: 'HT-2524',
                nurseryName: 'Texcumar',
                nurseryHtCode: 'HT-2525',
                naupliiCode: 'Chicpin K1',
                plantingDate: '10/02/24',
                harvestDate: '15/08/24',
                moduleNumber: 1,
                tankPondNumber: 1,
                densityPerM3: '100.000',
            },
            farm: {
                farmName: 'ShrimpCo Manabi',
                grCode: 'GR-5247',
                growingProtocol: 'Semi Intensive',
                productionProtocol: 'TriPhasic',
                waterManagingSystem: 'RAS',
                nurseryPond: 'Ppc#2',
                plantingDate: '12/02/24',
                initialNurseryDensity: 100,
                preGrowingPond: 'Ppe#3',
                transferDate: '20/04/24',
                initialPreGrowingDensity: 45,
                finalPreGrowingPond: 'Pef#34',
                finalTransferDate: '05/06/24',
                finalPreGrowingDensity: 15,
            },
            produccion: {
                feedMillHatchery: 'SCI-R004304',
                feedMillFarm: 'SCI-R004304',
            },
            tratamiento: {
                antibioticTreatment: 'SCI-R008978',
                initialDate: '01/03/24',
                endingDate: '15/03/24',
            },
            condiciones: {
                salinityPpm: 17,
                waterSourceType: 'Brackish',
                cycleWaterUse: '1750 m3/Ha',
                co2Footprint: '0.28 KgCO2/Shrimp Kg',
            },
            cosecha: {
                harvestProcess: 'Conventional',
                harvestDate: '15/08/24',
                harvestDensity: '8 u/m2',
                harvestTimeLapse: '02:30:45',
                harvestTemperature: '-6ºC',
            },
            custodia: {
                custodyTransportTimeLapse: '02:00:00',
                custodyTransportTemperature: '-4ºC',
                plantRegistryTemperature: '-4ºC',
            },
            calidad: {
                qualityLabTest: 'Approved',
                organolepticLabTest: 'Approved',
                sulphitesLabTest: 'Approved',
                microbiologicalLabTest: 'Approved',
                chemicalLabTest: 'Approved',
            },
        },
    ];