export const optionsInventory = [
    {
        categoria: "larva",
        items: [
            {
                codigo: "PL/10",
                nombre: "post larva 10",
                descripcion: "post larva para siembra en pre cria",
                info_adicional: "sistema de coordinacion AquaLink",
                nota_doc: "",
                peso_total_presentacion: "indeterminado",
                unidad_medida: "MILLAR",
                SKU: "094",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "PL/12",
                nombre: "post larva 12",
                descripcion: "post larva para siembra en pre cria",
                info_adicional: "sistema de coordinacion AquaLink",
                nota_doc: "",
                peso_total_presentacion: "indeterminado",
                unidad_medida: "MILLAR",
                SKU: "095",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "PL/14",
                nombre: "post larva 14",
                descripcion: "post larva para siembra en pre cria",
                info_adicional: "sistema de coordinacion AquaLink",
                nota_doc: "",
                peso_total_presentacion: "indeterminado",
                unidad_medida: "MILLAR",
                SKU: "096",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "PL/16",
                nombre: "post larva 16",
                descripcion: "post larva para siembra en pre cria",
                info_adicional: "sistema de coordinacion AquaLink",
                nota_doc: "",
                peso_total_presentacion: "indeterminado",
                unidad_medida: "MILLAR",
                SKU: "097",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "PL/18",
                nombre: "post larva 18",
                descripcion: "post larva para siembra en pre cria",
                info_adicional: "sistema de coordinacion AquaLink",
                nota_doc: "",
                peso_total_presentacion: "indeterminado",
                unidad_medida: "MILLAR",
                SKU: "098",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "PL/20",
                nombre: "post larva 20",
                descripcion: "post larva para siembra en pre cria",
                info_adicional: "sistema de coordinacion AquaLink",
                nota_doc: "",
                peso_total_presentacion: "indeterminado",
                unidad_medida: "MILLAR",
                SKU: "099",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            }
        ]
    },

    {
        categoria: "alimento balanceado",
        items: [
            {
                codigo: "AB45/600",
                nombre: "45% ESTRUIDO 600",
                descripcion: "Alimento Inicial 45%E / 600 micras",
                info_adicional: "Alimento Inicial Pre Cria Estandar",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "001",
                tipo: "estandar",
                proteina: "45%E",
                forma: "estruido",
                fase: "iniciador",
                tamanio: "600 micras",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB45/800",
                nombre: "45% ESTRUIDO 800",
                descripcion: "Alimento Inicial 45%E / 800 micras",
                info_adicional: "Alimento Inicial Pre Cria Estandar",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "002",
                tipo: "estandar",
                proteina: "45%E",
                forma: "estruido",
                fase: "iniciador",
                tamanio: "800 micras",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB45/1200",
                nombre: "45% ESTRUIDO 1200",
                descripcion: "Alimento Inicial 45%E / 1200 micras",
                info_adicional: "Alimento Inicial Pre Cria Estandar",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "003",
                tipo: "estandar",
                proteina: "45%E",
                forma: "estruido",
                fase: "iniciador",
                tamanio: "1200 micras",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB45/M",
                nombre: "45% MEDICADO 800-1200",
                descripcion: "Alimento medicado 45%E / 1200 micras",
                info_adicional: "Alimento Inicial Pre Cria medicado",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "004",
                tipo: "medicado",
                proteina: "45%E",
                forma: "estruido",
                fase: "iniciador",
                tamanio: "800-1200 micras",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB42/G",
                nombre: "42% GRANULADO 1200",
                descripcion: "Alimento Inicial 45%G / 1200 micras",
                info_adicional: "Alimento Inicial Pre Cria Estandar",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "005",
                tipo: "estandar",
                proteina: "42%G",
                forma: "granulado",
                fase: "iniciador",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB40/G",
                nombre: "40% GRANULADO 1200",
                descripcion: "Alimento Inicial 45%G / 1200 micras",
                info_adicional: "Alimento Inicial Pre Cria Estandar",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "006",
                tipo: "estandar",
                proteina: "40%G",
                forma: "granulado",
                fase: "iniciador",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB40/G",
                nombre: "40% GRANULADO 1200",
                descripcion: "Alimento Inicial 45%G / 1200 micras",
                info_adicional: "Alimento Inicial Pre Cria Estandar",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "007",
                tipo: "estandar",
                proteina: "40%AD",
                forma: "granulado",
                fase: "iniciador",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB40/M",
                nombre: "40% MEDICADO 800-1200",
                descripcion: "Alimento medicado 40%E / 1200 micras",
                info_adicional: "Alimento Inicial Pre Cria medicado",
                nota_doc: "Post larva de 0.001 a 1 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "009",
                tipo: "medicado",
                proteina: "40%E",
                forma: "estruido",
                fase: "iniciador",
                tamanio: "800-1200 micras",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB35/G",
                nombre: "35% GRANULADO 1200",
                descripcion: "Alimento engorde 35%G / 1200 micras",
                info_adicional: "Alimento Inicial Pre Cria Estandar",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "010",
                tipo: "estandar",
                proteina: "35%G",
                forma: "granulado",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB35/P",
                nombre: "35% PELETIZADO 1.2",
                descripcion: "Alimento engorde 35%G / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "011",
                tipo: "estandar",
                proteina: "35%G",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB35/E",
                nombre: "35% ESTRUIDO 1.2",
                descripcion: "Alimento engorde 35%G / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "012",
                tipo: "estandar",
                proteina: "35%G",
                forma: "estruido",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB35/M",
                nombre: "35% MEDICADO 1.2",
                descripcion: "Alimento engorde 35%G / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "013",
                tipo: "medicado",
                proteina: "35%M",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB35/C",
                nombre: "35% COMPENSADO 1.2",
                descripcion: "Alimento engorde 35%G / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "014",
                tipo: "agua dulce",
                proteina: "35%AD",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB32/P",
                nombre: "32% PELETIZADO 1.2",
                descripcion: "Alimento engorde 30%G / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "015",
                tipo: "estandar",
                proteina: "32%P",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB32/E",
                nombre: "32% ESTRUIDO 1.2",
                descripcion: "Alimento engorde 32%G / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "016",
                tipo: "estandar",
                proteina: "32%E",
                forma: "estruido",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB32/M",
                nombre: "32% MEDICADO 1.2",
                descripcion: "Alimento engorde 32%G / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "017",
                tipo: "medicado",
                proteina: "32%M",
                forma: "estruido",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB32/C",
                nombre: "32% COMPENSADO 1.2",
                descripcion: "Alimento engorde 32%C / 1.2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "018",
                tipo: "agua dulce",
                proteina: "32%C",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "1.2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB30/P",
                nombre: "30% PELETIZADO 1.5",
                descripcion: "Alimento engorde 30%P / 1.5 - 2.5 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "019",
                tipo: "estandar",
                proteina: "30%P",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "1.5 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB30/E",
                nombre: "30% ESTRUIDO 1.5",
                descripcion: "Alimento engorde 30%E / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "020",
                tipo: "estandar",
                proteina: "30%E",
                forma: "estruido",
                fase: "engorde",
                tamanio: "1.5 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB30/M",
                nombre: "30% MEDICADO 1.5",
                descripcion: "Alimento engorde 30%M / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "Juveniles de 1 a 4 gr",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "021",
                tipo: "medicado",
                proteina: "30%M",
                forma: "estruido",
                fase: "engorde",
                tamanio: "1.5 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB30/C",
                nombre: "30% COMPENSADO 1.5",
                descripcion: "Alimento engorde 30%C / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "022",
                tipo: "agua dulce",
                proteina: "30%C",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "1.5 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB28/P",
                nombre: "28% PELETIZADO 2",
                descripcion: "Alimento engorde 28%P / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "023",
                tipo: "estandar",
                proteina: "28%P",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB28/E",
                nombre: "28% ESTRUIDO 2",
                descripcion: "Alimento engorde 30%E / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "024",
                tipo: "estandar",
                proteina: "28%E",
                forma: "estruido",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB28/M",
                nombre: "28% MEDICADO 2",
                descripcion: "Alimento engorde 28%M / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "025",
                tipo: "medicado",
                proteina: "28%M",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB28/C",
                nombre: "28% COMPENSADO 2",
                descripcion: "Alimento engorde 28%C / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "026",
                tipo: "agua dulce",
                proteina: "28%C",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB27/P",
                nombre: "27% PELETIZADO 2",
                descripcion: "Alimento engorde 27%P / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "027",
                tipo: "estandar",
                proteina: "27%P",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB27/E",
                nombre: "27% ESTRUIDO 2",
                descripcion: "Alimento engorde 30%E / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "028",
                tipo: "estandar",
                proteina: "27%E",
                forma: "estruido",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB27/M",
                nombre: "27% MEDICADO 2",
                descripcion: "Alimento engorde 27%M / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "029",
                tipo: "medicado",
                proteina: "27%M",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB27/C",
                nombre: "27% COMPENSADO 2",
                descripcion: "Alimento engorde 27%P / 1.5 - 2 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "030",
                tipo: "agua dulce",
                proteina: "27%C",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB22/P",
                nombre: "22% PELETIZADO 2",
                descripcion: "Alimento engorde 22%P / 2.5 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "031",
                tipo: "estandar",
                proteina: "22%P",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB22/M",
                nombre: "22% MEDICADO 2",
                descripcion: "Alimento engorde 30%M / 2.5 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "032",
                tipo: "medicado",
                proteina: "22%M",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "AB22/C",
                nombre: "22% COMPENSADO 2",
                descripcion: "Alimento engorde 30%C / 2.5 mm",
                info_adicional: "Alimento Engorde",
                nota_doc: "adultos 4 grs en adelante",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "033",
                tipo: "agua dulce",
                proteina: "22%C",
                forma: "peletizado",
                fase: "engorde",
                tamanio: "2.5 mm",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            },
            {
                codigo: "ABxx/x",
                nombre: "n/a",
                descripcion: "n/d",
                info_adicional: "n/d",
                nota_doc: "n/d",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "100",
                tipo: "n/d",
                proteina: "n/d",
                forma: "n/d",
                fase: "engorde",
                tamanio: "n/d",
                origen: "organico",
                estado: "solido",
                presentacion: "25 kgs",
                certificacion: ""
            }

        ]
    }

    ,
    {
        categoria: "aditivos",
        items: [
            {
                codigo: "AD/MZ1",
                nombre: "Melaza",
                descripcion: "Pegante organico",
                info_adicional: "Fuente de Carbono",
                nota_doc: "",
                peso_total_presentacion: "30",
                unidad_medida: "kgs",
                SKU: "034",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/AP1",
                nombre: "Aceite de pescado",
                descripcion: "Atractante",
                info_adicional: "Fuente de Acidos Grasos",
                nota_doc: "",
                peso_total_presentacion: "20",
                unidad_medida: "lts",
                SKU: "035",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/NU1",
                nombre: "Nucleotido",
                descripcion: "Atractante",
                info_adicional: "Fuente de Acidos Grasos",
                nota_doc: "",
                peso_total_presentacion: "20",
                unidad_medida: "kgs",
                SKU: "038",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/PE1",
                nombre: "Pegante Liquido",
                descripcion: "Pegante Organico",
                info_adicional: "pegante para alimento balanceado",
                nota_doc: "",
                peso_total_presentacion: "1",
                unidad_medida: "kgs",
                SKU: "036",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/PE2",
                nombre: "Pegante Polvo",
                descripcion: "Pegante Organico",
                info_adicional: "pegante para alimento balanceado",
                nota_doc: "",
                peso_total_presentacion: "4",
                unidad_medida: "kgs",
                SKU: "037",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/PX1",
                nombre: "Peroxido",
                descripcion: "Agua Oxigenada",
                info_adicional: "control OD",
                nota_doc: "",
                peso_total_presentacion: "20",
                unidad_medida: "lts",
                SKU: "038",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/SP1",
                nombre: "Saponina",
                descripcion: "Control de Peces",
                info_adicional: "preparacion de piscina",
                nota_doc: "",
                peso_total_presentacion: "1",
                unidad_medida: "kgs",
                SKU: "039",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/SP2",
                nombre: "Saponina",
                descripcion: "Control de Peces",
                info_adicional: "preparacion de piscina",
                nota_doc: "",
                peso_total_presentacion: "25",
                unidad_medida: "kgs",
                SKU: "",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/BB1",
                nombre: "Barbasco",
                descripcion: "Control de Peces",
                info_adicional: "preparacion de piscina",
                nota_doc: "",
                peso_total_presentacion: "10",
                unidad_medida: "lts",
                SKU: "040",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AD/CP1",
                nombre: "Matafish",
                descripcion: "Control de Peces",
                info_adicional: "preparacion de piscina",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            }
        ]
    }

    ,
    {
        categoria: "vitaminas",
        items: [
            {
                codigo: "VT/C35",
                nombre: "vitamina C35 MF",
                descripcion: "Vitamina C 35 monofosfatada",
                info_adicional: "mejoramiento de salud animal",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "042",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "VT/MV1",
                nombre: "multivitaminicos",
                descripcion: "Compuesto multivitaminico",
                info_adicional: "mejoramiento de salud animal",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "043",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "VT/IN1",
                nombre: "inmuno estimulantes",
                descripcion: "Estimulante de sistema inmune",
                info_adicional: "mejoramiento de salud animal",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "044",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            }
        ]
    },
    {
        categoria: "acidos organicos",
        items: [
            {
                codigo: "AO/S01",
                nombre: "Acido Organico 4",
                descripcion: "tratamiento preventivo y curativo",
                info_adicional: "",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "045",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AO/S02",
                nombre: "Acido Organico 20",
                descripcion: "tratamiento preventivo y curativo",
                info_adicional: "",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "046",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            },
            {
                codigo: "AO/P01",
                nombre: "Acido Organico P",
                descripcion: "tratamiento preventivo y curativo",
                info_adicional: "",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "047",
                tipo: "",
                proteina: "",
                forma: "",
                fase: "",
                tamanio: "",
                origen: "",
                estado: "",
                presentacion: "",
                certificacion: ""
            }
        ]
    }
    ,
    {
        categoria: "bacterias / enzimas",
        items: [
            {
                codigo: "BC/S01",
                nombre: "Bacteria Polvo 1",
                descripcion: "bacteria en polvo 1",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "048"
            },
            {
                codigo: "BC/S02",
                nombre: "Bacteria Polvo 5",
                descripcion: "bacteria en polvo 5",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "049"
            },
            {
                codigo: "BC/L01",
                nombre: "Bacteria Liquido 1L",
                descripcion: "bacteria liquida 1",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "050"
            },
            {
                codigo: "BC/L02",
                nombre: "Bacteria Liquido 4L",
                descripcion: "bacteria liquida 4",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "051"
            },
            {
                codigo: "BC/P01",
                nombre: "Bacteria Pastillas 5",
                descripcion: "bacteria en pastillas o discos",
                info_adicional: "bioremediacion suelo y agua",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "052"
            },
            {
                codigo: "BC/P02",
                nombre: "Bacteria Pastillas 10",
                descripcion: "bacteria en pastillas o discos",
                info_adicional: "bioremediacion suelo y agua",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "053"
            },
            {
                codigo: "BC/B01",
                nombre: "Bacttria Bioremediacion L",
                descripcion: "",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "054"
            }
        ]
    }
    ,
    {
        categoria: "minerales y calcicos",
        items: [
            {
                codigo: "CM/001",
                nombre: "Cal Viva",
                descripcion: "calcareo desinfectante",
                info_adicional: "",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: ""
            },
            {
                codigo: "CM/002",
                nombre: "Cal P24",
                descripcion: "calcareo desinfectante",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "055"
            },
            {
                codigo: "CM/003",
                nombre: "Carbonato de Calcio",
                descripcion: "calcareo estabilizador",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "056"
            },
            {
                codigo: "CM/004",
                nombre: "Hidroxido de Calcio",
                descripcion: "calcareo estabilizador",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "057"
            },
            {
                codigo: "CM/005",
                nombre: "Zeolita",
                descripcion: "calcareo estabilizador",
                info_adicional: "tratamiento preventivo y curativo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "058"
            },
            {
                codigo: "CM/006",
                nombre: "Magnesio",
                descripcion: "Cloruro de Magnesio",
                info_adicional: "compensador de balance ionico",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "059"
            },
            {
                codigo: "CM/007",
                nombre: "Potasio",
                descripcion: "Cloruro de Potasio",
                info_adicional: "compensador de balance ionico",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "060"
            },
            {
                codigo: "CM/008",
                nombre: "Metasilicato de Sodio",
                descripcion: "Metasilicato de Sodio",
                info_adicional: "compensador de balance ionico",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "061"
            },
            {
                codigo: "CM/009",
                nombre: "Pecarbonato de Sodio",
                descripcion: "Pecarbonato de Sodio",
                info_adicional: "compensador de balance ionico",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "062"
            }
        ]
    }
    ,





    {
        categoria: "desparasitantes",
        items: [
            {
                codigo: "DP/BC1",
                nombre: "Bactericida L",
                descripcion: "tratamiento preventivo y curativo",
                info_adicional: "bactericida liquido",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "063"
            },
            {
                codigo: "DP/BC2",
                nombre: "Bactericida P",
                descripcion: "tratamiento preventivo y curativo",
                info_adicional: "bactericida en polvo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "064"
            },
            {
                codigo: "DP/AP1",
                nombre: "Antiparasitario L",
                descripcion: "tratamiento preventivo y curativo",
                info_adicional: "antiparasitario liquido",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "065"
            },
            {
                codigo: "DP/AP2",
                nombre: "Antiparasitario P",
                descripcion: "tratamiento preventivo y curativo",
                info_adicional: "antiparasitario en polvo",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "066"
            }
        ]
    },
    {
        categoria: "fertilizantes",
        items: [
            {
                codigo: "FT/SA1",
                nombre: "Silicato Acuicola",
                descripcion: "promotor de diatomeas",
                info_adicional: "fertilizante organico mineral",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "067"
            },
            {
                codigo: "FT/NI1",
                nombre: "Nitrato de Sodio",
                descripcion: "compensacion nitrogeno",
                info_adicional: "fertilizante organico mineral",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "068"
            },
            {
                codigo: "FT/DAP",
                nombre: "DAP",
                descripcion: "promotor de nitrogeno y fosforo",
                info_adicional: "fertilizante organico mineral",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "069"
            }
        ]
    },
    {
        categoria: "medicados",
        items: [
            {
                codigo: "MD/001",
                nombre: "ANTIBIOTICO OXI",
                descripcion: "curativo",
                info_adicional: "medicado controlado",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "070"
            },
            {
                codigo: "MD/002",
                nombre: "ANTIBIOTICO FLO",
                descripcion: "curativo",
                info_adicional: "medicado controlado",
                nota_doc: "",
                peso_total_presentacion: "",
                unidad_medida: "",
                SKU: "071"
            }
        ]
    }

];



export const sampleData = [
    {
        key: '1',
        categoria: 'alimento balanceado',
        codigo: 'AB45/600',
        nombre: '45% ESTRUIDO 600',
        descripcion: 'Alimento Inicial 45%E / 600 micras',
        marca: 'Marca A',
        modelo: 'Modelo 1',
        precio_lista: 200,
        precio_unidad_medida: 50,
        unidad_medida: 'kgs'
    },
    {
        key: '2',
        categoria: 'alimento balanceado',
        codigo: 'AB45/800',
        nombre: '45% ESTRUIDO 800',
        descripcion: 'Alimento Inicial 45%E / 800 micras',
        marca: 'Marca B',
        modelo: 'Modelo 2',
        precio_lista: 250,
        precio_unidad_medida: 60,
        unidad_medida: 'kgs'
    },
    {
        key: '3',
        categoria: 'alimento balanceado',
        codigo: 'AB40/G',
        nombre: '40% GRANULADO 1200',
        descripcion: 'Alimento Inicial 40%G / 1200 micras',
        marca: 'Marca C',
        modelo: 'Modelo 3',
        precio_lista: 220,
        precio_unidad_medida: 55,
        unidad_medida: 'kgs'
    },
    {
        key: '4',
        categoria: 'alimento balanceado',
        codigo: 'AB35/E',
        nombre: '35% ESTRUIDO 1.2',
        descripcion: 'Alimento engorde 35%G / 1.2 mm',
        marca: 'Marca D',
        modelo: 'Modelo 4',
        precio_lista: 180,
        precio_unidad_medida: 45,
        unidad_medida: 'kgs'
    },

    // Aditivos
    {
        key: '5',
        categoria: 'aditivos',
        codigo: 'AD/MZ1',
        nombre: 'Melaza',
        descripcion: 'Pegante organico',
        marca: 'Marca E',
        modelo: 'Modelo 5',
        precio_lista: 100,
        precio_unidad_medida: 20,
        unidad_medida: 'kgs'
    },
    {
        key: '6',
        categoria: 'aditivos',
        codigo: 'AD/AP1',
        nombre: 'Aceite de pescado',
        descripcion: 'Atractante, fuente de ácidos grasos',
        marca: 'Marca F',
        modelo: 'Modelo 6',
        precio_lista: 300,
        precio_unidad_medida: 60,
        unidad_medida: 'lts'
    },
    {
        key: '7',
        categoria: 'aditivos',
        codigo: 'AD/PE1',
        nombre: 'Pegante Líquido',
        descripcion: 'Pegante Orgánico para alimento balanceado',
        marca: 'Marca G',
        modelo: 'Modelo 7',
        precio_lista: 150,
        precio_unidad_medida: 30,
        unidad_medida: 'kgs'
    },

    // Vitaminas
    {
        key: '8',
        categoria: 'vitaminas',
        codigo: 'VT/C35',
        nombre: 'Vitamina C35 MF',
        descripcion: 'Vitamina C 35 monofosfatada',
        marca: 'Marca H',
        modelo: 'Modelo 8',
        precio_lista: 400,
        precio_unidad_medida: 100,
        unidad_medida: 'kgs'
    },
    {
        key: '9',
        categoria: 'vitaminas',
        codigo: 'VT/MV1',
        nombre: 'Multivitamínicos',
        descripcion: 'Compuesto multivitamínico',
        marca: 'Marca I',
        modelo: 'Modelo 9',
        precio_lista: 350,
        precio_unidad_medida: 87.5,
        unidad_medida: 'kgs'
    },
    {
        key: '10',
        categoria: 'vitaminas',
        codigo: 'VT/IN1',
        nombre: 'Inmunoestimulantes',
        descripcion: 'Estimulante del sistema inmune',
        marca: 'Marca J',
        modelo: 'Modelo 10',
        precio_lista: 420,
        precio_unidad_medida: 105,
        unidad_medida: 'kgs'
    },

    // Ácidos Orgánicos
    {
        key: '11',
        categoria: 'acidos organicos',
        codigo: 'AO/S01',
        nombre: 'Ácido Orgánico 4',
        descripcion: 'Tratamiento preventivo y curativo',
        marca: 'Marca K',
        modelo: 'Modelo 11',
        precio_lista: 230,
        precio_unidad_medida: 57.5,
        unidad_medida: 'lts'
    },
    {
        key: '12',
        categoria: 'acidos organicos',
        codigo: 'AO/S02',
        nombre: 'Ácido Orgánico 20',
        descripcion: 'Tratamiento preventivo y curativo',
        marca: 'Marca L',
        modelo: 'Modelo 12',
        precio_lista: 210,
        precio_unidad_medida: 52.5,
        unidad_medida: 'lts'
    },

    // Desparasitantes
    {
        key: '13',
        categoria: 'desparasitantes',
        codigo: 'DP/BC1',
        nombre: 'Bactericida L',
        descripcion: 'Tratamiento preventivo y curativo, bactericida líquido',
        marca: 'Marca M',
        modelo: 'Modelo 13',
        precio_lista: 175,
        precio_unidad_medida: 35,
        unidad_medida: 'lts'
    },
    {
        key: '14',
        categoria: 'desparasitantes',
        codigo: 'DP/AP1',
        nombre: 'Antiparasitario L',
        descripcion: 'Tratamiento preventivo y curativo, antiparasitario líquido',
        marca: 'Marca N',
        modelo: 'Modelo 14',
        precio_lista: 195,
        precio_unidad_medida: 39,
        unidad_medida: 'lts'
    },

    // Fertilizantes
    {
        key: '15',
        categoria: 'fertilizantes',
        codigo: 'FT/SA1',
        nombre: 'Silicato Acuícola',
        descripcion: 'Promotor de diatomeas',
        marca: 'Marca O',
        modelo: 'Modelo 15',
        precio_lista: 285,
        precio_unidad_medida: 57,
        unidad_medida: 'kgs'
    },
    {
        key: '16',
        categoria: 'fertilizantes',
        codigo: 'FT/NI1',
        nombre: 'Nitrato de Sodio',
        descripcion: 'Compensación de nitrógeno',
        marca: 'Marca P',
        modelo: 'Modelo 16',
        precio_lista: 320,
        precio_unidad_medida: 64,
        unidad_medida: 'kgs'
    },
    {
        key: '17',
        categoria: 'fertilizantes',
        codigo: 'FT/DAP',
        nombre: 'DAP',
        descripcion: 'Promotor de nitrógeno y fósforo',
        marca: 'Marca Q',
        modelo: 'Modelo 17',
        precio_lista: 290,
        precio_unidad_medida: 58,
        unidad_medida: 'kgs'
    },

    // Medicados
    {
        key: '18',
        categoria: 'medicados',
        codigo: 'MD/001',
        nombre: 'ANTIBIOTICO OXI',
        descripcion: 'Curativo, medicado controlado',
        marca: 'Marca R',
        modelo: 'Modelo 18',
        precio_lista: 510,
        precio_unidad_medida: 102,
        unidad_medida: 'kgs'
    },
    {
        key: '19',
        categoria: 'medicados',
        codigo: 'MD/002',
        nombre: 'ANTIBIOTICO FLO',
        descripcion: 'Curativo, medicado controlado',
        marca: 'Marca S',
        modelo: 'Modelo 19',
        precio_lista: 530,
        precio_unidad_medida: 106,
        unidad_medida: 'kgs'
    }
];